spring.application.name=employee-management-system

#Mysql database properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=MySecretKeyForJWTGenerationMySecretKeyForJWTGeneration
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG